### PR TITLE
Use rvic 1.1.1 and resolve its internal issues

### LINKED ISSUE #30: Update RVIC version to 1.1.1
RVIC 1.1.1 is now available at the [Pypi server](https://pypi.pacificclimate.org/simple/rvic/). Update `osprey` to use the new version of RVIC.

### PR DESCRIPTION
**Pull request by sum1lim**
This PR resolve #30 

RVIC 1.1.1 is included in `requrements.txt`. However, the issues addressed in our [initial research](https://github.com/pacificclimate/osprey/issues/5#issuecomment-658293189) are not resolved in the latest RVIC version. The `.ix` deprecation error is resolved in this PR by downgrading pandas to `pandas<0.20.0`, but `core/share.py` still needs to be modified manually after the installation.

CI pytest should remain the same until the remaining RVIC internal issue is solved.

Edit: Numpy version downgraded to `numpy<1.18.0` since [numpy/testing/decorators.py has been removed](https://numpy.org/doc/stable/release/1.18.0-notes.html?highlight=numpy%20testing%20decorators#expired-deprecations) from the 1.18.0 version release, which caused `ModuleNotFoundError: No module named 'numpy.testing.decorators'` after the pandas downgrade.

### CODE REVIEW

**Comment by eyvorchuk** [comment]
The `convolution` test with the `.cfg` file works, but the one with the dictionary fails.

**Comment by sum1lim** [comment]
@eyvorchuk pytest is working just fine in my workstation. Could you copy and paste the error messages?

**Comment by eyvorchuk** [comment]
```bash
(osprey-venv) slim@pcic-0011:~/osprey$ pytest tests/test_wps_convolution.py 
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/slim/osprey, inifile: setup.cfg
plugins: nbval-0.9.5, requests-mock-1.8.0, flake8-1.0.6, notebook-0.6.0
collected 2 items                                                              

tests/test_wps_convolution.py .F                                         [100%]

=================================== FAILURES ===================================
________________________ test_wps_convolution[config1] _________________________
Traceback (most recent call last):
  File "/home/slim/osprey/tests/test_wps_convolution.py", line 38, in test_wps_convolution
    run_wps_process(Convolution(), params)
  File "/home/slim/osprey-venv/lib/python3.6/site-packages/wps_tools/testing.py", line 65, in run_wps_process
    assert_response_success(resp)
  File "/home/slim/osprey-venv/lib/python3.6/site-packages/pywps/tests.py", line 145, in assert_response_success
    assert len(success) == 1
AssertionError
```

**Comment by sum1lim** [comment]
@eyvorchuk it should be good now.

**Review by jameshiebert — CHANGES_REQUESTED** [review]
I think that we need to come up with a better solution here than limiting `pandas` to a version that's pre-0.20. pandas==0.19.2 was released on *December 24, 2016* (almost 4 years ago). While Python 3.7's first alpha [wasn't even released until nine months later](https://www.python.org/dev/peps/pep-0537/#id12).

Hence, limiting the testing to py36 isn't just about getting the CI to run. It's that this software, as written, will not work on any contemporary (post-36) versions of Python. That's untenable, in my opinion. We need to find a way to get this to work on a recent version of `pandas`, ideally a `>1.0` version which has been released this year.

**Comment by sum1lim** [comment]
@jameshiebert I tried to come up with solutions to the dependency issues, but it was nearly impossible to find one for a software with the last update in 2017. Also, the attempts were only to resolve one of the RVIC issues (pandas' `.ix` deprecation error), and we still do not know an actual reason for [another issue](https://github.com/UW-Hydro/RVIC/issues/96). Therefore, a python script `resolve_rvic_issues` was implemented to resolve both issues by modifying RVIC's source code. Running this script is now a part of `osprey`'s installation process and is applied to CI actions and `Makefile`.

**Comment by nikola-rados** [comment]
Is it worth us just making a fork? It doesn't seem like they are maintaining the repo anymore. I would prefer doing that to adjusting the source code with `make`. Thoughts on this @jameshiebert ?

**Comment by jameshiebert** [comment]
Yeah, I don't like the idea of patching the source with `make`. It's super hacky. Let's discuss the fork idea offline.

**Pull request closed without merging**
