### PR TITLE
Revert stdout and stderr to default when RecursionError is encountered

### LINKED ISSUE #57: Successive RecursionErrors
**Describe the bug**
`RecursionError` occurs whenever an osprey process is run after a failed attempt OR running multiple processes at the same time, and it causes failures in succeeding processes as well. 
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**To Reproduce**
1. Run `jupyter lab`
2. Run processes with invalid inputs 
3. See error logs
4. Follow the above procedure in a fresh Docker container but with running multiple processes at the same time

**Expected behavior**
Enable running a process after a failed attempt.

### PR DESCRIPTION
**Pull request by sum1lim**
resolves #57 

For reviewing, change `docker_url` to `http://docker-dev03.pcic.uvic.ca:30124/wps` in `jupyter lab` demos

### CODE REVIEW

**Review by cairosanders — APPROVED** [review]
Looks good!

**Comment by nikola-rados** [comment]
This solution seems to do the trick. But I'm interested in finding out what exactly is causing it. You mention in the issue that invalid input cause the recursion error. What about these input does that? Should we be screening these inputs before starting the process? It feels like there are some more questions we should answer before moving forward.

**Comment by sum1lim** [comment]
@nikola-rados I guess I did not describe the bug clearly. As the title of the issue suggests, the `RecursionError` is caused by an unsuccessful RVIC process. Running processes with invalid inputs or running multiple processes at the same time is just to generate that `RecursionError` from the following process. Once `RecursionError` has occurred, the Docker container hosting `osprey` is corrupted and no longer works unless a fresh container is up. It is hard to describe in the text, but it would be a lot easier to understand by comparing the logs produced when running the `master` version and this branch. This PR is to investigate where the `RecursionError` is coming from and resolve the bug.

I have identified that RVIC processes [set stdout and stderr](https://github.com/pacificclimate/rvic-daccs/blob/master/rvic/core/log.py#L74) to custom [fake stream files](https://github.com/pacificclimate/rvic-daccs/blob/master/rvic/core/log.py#L18). But when the processes are halted due to an error caused by certain reasons (invalid inputs OR running multiple processes), the [close_logger](https://github.com/pacificclimate/rvic-daccs/blob/master/rvic/core/log.py#L90) function is never called, and `stdout` and `stderr` are not reverted back to the default, which affects the following process run in the same 'corrupted' Docker container.

> Should we be screening these inputs before starting the process?

I think it is a good idea to have our own method of screening the inputs before running processes since it looks like RVIC is not handling its own error very well, but it is not really relevant to this issue and PR. I think it will be better to write a separate issue and move on.

**Comment by nikola-rados** [comment]
Would screening the inputs beforehand prevent us from having to use `close_logger`?

**Comment by sum1lim** [comment]
> Would screening the inputs beforehand prevent us from having to use close_logger?

Not really. I have identified that running multiple processes at the same time halts the software unsuccessfully, which causes `RecursionError`. And there could possibly be so many other cases that cannot be dealt with by screening the inputs. I think it is ideal to call `close_logger` since it is a must to run function for each RVIC process, and if RVIC fails to call it, it is important that `osprey` makes sure to call it before the future process runs.

**Review by nikola-rados — APPROVED** [review]
LGTM

**Pull request merged**
